
name: Maven WAR Build

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Maven
        run: mvn -B -ntp -q clean package
      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: distance-api-war
          path: target/distance-api.war
